spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_buddies # PostgreSQL database connection URL
    username: # Database username
    password: Password # Database password
    driver-class-name: org.postgresql.Driver # PostgreSQL driver class
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the schema
    show-sql: false # Hides SQL queries in the logs
    properties:
      hibernate:
        format_sql: true # Formats SQL logs
    database: postgresql # Specifies the database type
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Specifies the Hibernate dialect
  mail:
    host: localhost
    port: 1025 # Mail server configuration (likely for local testing)
    username: raj
    password: password
    properties:
      mail:
        smtp:
          trust: "*" # Trusts all mail servers
          auth: true # Enables authentication
          starttls:
            enable: true # Enables STARTTLS
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: c5690098e9acf28357df9bed86540875695afd0fc3ab8f7a16ce79efbf698503 # JWT secret key
      expiration: 8640000 # JWT expiration time
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account # Activation URL for frontend